### ISSUE TITLE
ducky script ALT combinations not working

### ISSUE THREAD

**Issue by johnybravo3364** [michalmonday/supremeDuck#2]
hi
on ducky script , "ALT TAB" "ALT SPACE" and other ALT combinations dont work.

but when i click on "Alt+Tab" button it work.

**Comment by michalmonday** [comment]
Hi, thanks a lot for letting know, I'll try to fix it and I'll update the app.

**Comment by johnybravo3364** [comment]
np , thanks to you for your work .
my test was with wifi connection

**Comment by michalmonday** [comment]
I just updated the source files, it is necessary to reupload/reinstall both: Android app and Arduino code.
I'll also update the google play store app but it may take some time until it's live (the updated version is 1.07).

In case if you encounter any more issues it would be cool if you created another issue, thanks.

**Comment by johnybravo3364** [comment]
thanks alot , will test now , glad to see project still developed

**Comment by johnybravo3364** [comment]
fixed
