### ISSUE TITLE
CJMCU-3212

### ISSUE THREAD

**Issue by Neogamezzz** [michalmonday/supremeDuck#4]
How to flashing CJMCU-3212 for using SupremeDuck with WiFi?
https://s.click.aliexpress.com/e/94HHfjS
Or Cactus WHID.
https://s.click.aliexpress.com/e/so1IlmC

**Comment by michalmonday** [comment]
Hi, here's guide on how to flash the [Esp8266.bin](https://github.com/michalmonday/supremeDuck/blob/master/source/Esp8266%20version%20stuff/Esp8266.bin) to Esp-12F located on CJMCU-3212:
https://github.com/puckk/CJMCU-3212

Notice that suggested way involves uploading [separate code](https://github.com/puckk/CJMCU-3212/blob/master/step1.ino) to the Atmega32u4. After that it suggests using esptool.py but the [Nodemcu flasher](https://github.com/nodemcu/nodemcu-flasher) also could be used. After flashing the Esp-12F all you have to do is upload the [supremeDuck code](https://github.com/michalmonday/supremeDuck/tree/master/source/supremeDuck) to the board (make sure to download the whole folder) and it should work I guess but I never used these boards.

If you do not already own these boards but only think about buying one then I would suggest to buy mine instead, today I received 3 PCBs and the design seems to work. I could sell you 1 for £15 if you'd like to. It's smaller than the boards you mentioned and has a switch (that can be used to program Esp8266 without the need to upload [the separate code](https://github.com/puckk/CJMCU-3212/blob/master/step1.ino) mentioned above, as long as supremeDuck code is loaded into it).

![board image](https://i.imgur.com/1a0621f.jpg)
